[package]
name = "flock-signal-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
flock-adapter = { path = "../../rust/flock-adapter" }
event-correlator = { path = "../../rust/event-correlator" }
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
tokio.workspace = true
subtle.workspace = true
uuid.workspace = true
